model:
  baseline_weights: yolo11m.pt
  classes:
  - 0
  conf_threshold: 0.3
  device: cpu
  imgsz: 960
  weights: output_runs/best.pt
rules:
  movement_tolerance: 25.0
  roi:
  - - 438
    - 114
  - - 1477
    - 126
  - - 1678
    - 802
  - - 247
    - 770
  time_threshold: 5.0
tracking:
  tracker: config/bytetrack_custom.yaml
video:
  output_dir: output
  source: data/sample.mp4
